# To run all pre-commit checks, use:
#
#     pre-commit run -a
#
# To install pre-commit hooks that run every time you commit:
#
#     pre-commit install
#

ci:
  autoupdate_commit_msg: "â¬†ï¸ğŸª update pre-commit hooks"
  autofix_commit_msg: "ğŸ¨ pre-commit fixes"

repos:
  # Clang-format the C++ part of the code base automatically
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev:  v18.1.8
    hooks:
      - id: clang-format
        types_or: [ c++, c, cuda ]

  # CMake format the CMakeLists.txt files
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: [pyyaml]
        types: [file]
        files: (\.cmake|CMakeLists.txt)(.in)?$
